### ISSUE TITLE
Баг экспорта  "Схема почтовых событий"

### ISSUE THREAD

**Issue by konstantin-s** [konstantin-s/sprint.migration#3]
В процессе экспорта (Sprint\Migration\Schema\EventSchema::export())  EventTypes и EventMessages производится разбивка по строкам в массив и на каждое значение еще делается trim
![image](https://user-images.githubusercontent.com/9697235/65602019-9a795780-dfbc-11e9-9781-8b3dfa8266a3.png)
![image](https://user-images.githubusercontent.com/9697235/65602127-c98fc900-dfbc-11e9-9a36-d8e54fa84e3d.png)

Что приводит к тому, что строки, содержащие только пробел, преобразовывались в пустые строки и сохранялись в файл экспорта
В БД в шаблоне есть пробел, в JSON он пропал:
![image](https://user-images.githubusercontent.com/9697235/65607175-85ed8d00-dfc5-11e9-90e3-4ab66098ef2c.png)
  
В итоге это приводило к ложному срабатыванию при проверке наличия отличий между  EventType/EventMessage в схеме и в БД
и в итоге "Схема почтовых событий" всегда была помечена как новая и её импорт этого не менял

**Comment by konstantin-s** [comment]
Исправлено тем, что убран trim

**Comment by andreyryabin** [comment]
странно, это преобразование должно быть для 2х сравниваемых схем, а происходит с одной?

**Comment by andreyryabin** [comment]
аа, prepareExportEventMessage вообще там не участвует, ок
